### PR TITLE
refactor and add stiffness support

### PR DESCRIPTION
**Pull request by Marco9700**
Hi kenji, I tested the new branch rolling stiffness and nao_lola notefied me that the indexes array has the wrong length (should be 25, not 27) .In the parser.cpp I reduced the length of the array stiffnessMax to 25 and the errors disappeared so I suggest you to do that too (I attach below the screenshots of the errors).Unfortunatly the stiffnesses of the joints still remains set to 1.0 at the end of the action sit.pos even after this change I made.
Schermata del 2023-05-19 13-20-30

### CODE REVIEW

**Comment by ijnek** [comment]
Hi @Marco9700, could you please pull the most recent change and give it another try?

Just some things to keep in mind when dealing with stiffness lines in a pos file:

* By [definition of the pos files](https://github.com/UNSWComputing/rUNSWift-2019-release/blob/main/image/home/nao/data/pos/README.md), a position line must follow a stiffness line, or it won't take effect. So you can't have a stiffness line at the end of a pos file. You'll need a position line that follows it to take effect.

* You must specify stiffness before **each position line** if you want to use non-zero stiffness for the following position line. If a stiffness line is not present the position will be executed with stiffness 1.0 for all joints.

**Comment by Marco9700** [comment]
I'm using the runswift's .pos files and each line with '$' is followed by one with '!'.
Unfortunately with the new release,the nao_lola node gives some errors related to the size of the indexes of the stiffness(could the problem be in the line 33 of the parser.cpp  `.set_indexes(indexes)` ?) I also checked if the stiffnesses are modified after the action but they remain set to 1.0.Below you can find a screenshot about the situation. 
Schermata del 2023-05-23 12-09-20

**Comment by ijnek** [comment]
Hi @Marco9700, there was a missing set__indexes later on (https://github.com/ijnek/naosoccer_pos_action/commit/c82ed0d19e5cc4a8a74e116bfe3098df31401c31). This is now fixed. Please give it another try!

**Comment by Marco9700** [comment]
Hi @ijnek sorry if I didn't answer before but I couldn't went to the laboratory to test the changes until today. By adding set__indexes as you told me in the previous release now I'm able to change both the positions and the stiffnesses of the joints using the .pos files, so thank you for the help. I also saw that you merged the rolling-stiffness branch into the main one. Did you keep the last changes and implemented the parser.cpp code directly into the new linear.cpp? Does the nao behaves the same way if I replace the rolling-stiffness branch I have just tested with the current main one?

**Comment by ijnek** [comment]
Hi @Marco9700, I'm not quite sure but it looks like I've accidentally deleted the rolling-stiffness branch. I was planning on merging that into rolling (the main branch) once the changes were tested. I'll get a PR re-opened.

Please see #7

**Pull request closed without merging**
